fix unhelpful message in browser
In the browser, WebTorrent’s `client.seed()` function returns “Uncaught
TypeError: fs.stat is not a function” when passing in a file path,
because fs.readdir is defined by brfs (I think). Let’s check for
fs.stat instead.

For https://github.com/feross/webtorrent/issues/495#event-480750653